version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: development
      PGPORT: 5435
    ports:
      - "5435:5435"

  background:
    build: .
    command: >
      ./bin/jobs
    volumes:
      - .:/app
    depends_on:
      - db
      - web
    environment:
      RAILS_ENV: development

  web:
    build: .
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3005"]
    volumes:
      - .:/app
    ports:
      - "3005:3005"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
