default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  username: postgres
  password: password
  port: 5435

development:
  <<: *default
  database: development
  port: <%= ENV.fetch('POSTGRES_PORT', '5435') %>
  host: <%= ENV.fetch('DATABASE_HOST', 'db') %>
  username: <%= ENV.fetch('DATABASE_USER', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'password') %>

test:
  <<: *default
  database: test

production:
  <<: *default
  database: production